### ISSUE TITLE
Artifact Power Errors

### ISSUE THREAD

**Issue by behub-au** [Vladinator89/wow-addon-miniloot#1]
Not always but after consuming some Artifact tokens this error message occurs and will not go away without a reloadui.

> Message: Interface\AddOns\MiniLoot\core.lua:422: attempt to perform arithmetic on field '?' (a nil value)
> Time: 07/10/16 10:33:09
> Count: 1
> Stack: [C]: ?
> Interface\AddOns\MiniLoot\core.lua:422: in function `Tick'
> Interface\AddOns\MiniLoot\core.lua:686: in function <Interface\AddOns\MiniLoot\core.lua:680>
> 
> Locals:

**Comment by Vladinator** [comment]
Sorry for the slow reply. I need to turn on e-mail notifications. I tracked down the error. Seems that the numbers use locale thousands separator and I had forgotten to account for those cases. The latest release should have that fixed.
