### ISSUE TITLE
Original Loot roll messages still shows up.

### ISSUE THREAD

**Issue by Tarkumi** [Vladinator89/wow-addon-miniloot#3]
When I roll for an item, Miniloot's message shows up, but after it, the original "[Loot] You have selected...", "[Loot] You rolled ...." and "[Loot] XY (Rolled - xx) Won..." messages still appears.

**Comment by Tarkumi** [comment]
When I roll for an item, Miniloot's message shows up, but after it, the original "[Loot] You have selected...", "[Loot] You rolled ...." and "[Loot] XY (Rolled - xx) Won..." messages still appears.

**Comment by Vladinator** [comment]
It should hide all messages it reads. Just to be sure, make sure you are not ignoring the roll related checkboxes in the options:
http://imgur.com/a/zoHDZ

You can also try to uncheck this and see how it behaves:
http://imgur.com/a/5TJxh

What language is your game client in? I have tested it on many languages, did some tests, but haven't tested everything, so this might be a bug. :)

**Comment by Tarkumi** [comment]
I checked Miniloot's settings, they are not ignored.
When I uncheck the Item Loot settings, I don't get any loot messages from Miniloot.

But I noticed something else:
I'm using Tradeskillmaster, and enabled the option to replace auctions sold messages. When one of my auctions are sold, it replaces the messages, but sometimes the original message still appears after that.
Maybe there's a bug on Blizzard's end and chat messages get through even if you suppress them in an addon.

**Comment by Vladinator** [comment]
It could be that, or another addon interfering. If you are using the English client, I am using it as well, and I am not getting the same issue.

**Comment by Tarkumi** [comment]
I'm using the english client too.
I will try to disable other addons and check which one is interfering.
Thanks for you help.

**Comment by Vladinator** [comment]
I really want you to enjoy the addon. I hope you figure out the addon causing this. :)

**Comment by Vladinator** [comment]
It's been 3 years. I hope you solved the issue.
